### ISSUE TITLE
Shader build error on startup

### ISSUE THREAD

**Issue by kvark** [anopara/country-slice#2]
```
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: Some(4), srgb: true }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "ERROR::SHADER::COMPILATION_FAILED\n0:52(14): warning: `i' used uninitialized\n0:52(42): warning: `i' used uninitialized\n0:0(0): error: Read from write-only variable `cmds'\n\n#version 430\nlayout(local_size_x = 1, local_size_y = 1) in;\n\n// Same as the OpenGL defined struct: DrawElementsIndirectCommand\nstruct DrawCommand {\n    uint count;         // Num elements (vertices)\n    uint instanceCount; // Number of instances to draw (a.k.a primcount)\n    uint firstIndex;    // Specifies a byte offset (cast to a pointer type) into the buffer bound to GL_ELEMENT_ARRAY_BUFFER to start reading indices from.\n    uint baseVertex;    // Specifies a constant that should be added to each element of indices\u{200b} when chosing elements from the enabled vertex arrays.\n    uint baseInstance;  // Specifies the base instance for use in fetching instanced vertex attributes.\n};\n\n// Command buffer backed by a Shader Storage Object Buffer (SSBO)\nlayout(std140, binding = 0) writeonly buffer draw_commands {\n    DrawCommand cmds[];\n};\n\nlayout (std430, binding=2) buffer transforms_buffer { \n    mat4 transforms[];\n};\n\nstruct CurveData {\n    uint points_count;\n    uint pad0;\n    uint pad1;\n    uint pad2;\n    vec4 positions[1000];\n};\n\nlayout (std430, binding=3) buffer curves_buffer { \n    CurveData curves[];\n};\n\nlayout(rgba32f) uniform image2D road_mask;\n\nvoid main() {\n\n    const uint idx = gl_GlobalInvocationID.x;\n    //cmds[0].count = 312; // brick.glb vertex count\n    uint instance_offset = atomicAdd(cmds[0].instanceCount, curves[idx].points_count); //https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/atomicAdd.xhtml\n    //cmds[0].instanceCount = curves[idx].points_count;\n    //cmds[0].firstIndex = 0;   \n    //cmds[0].baseVertex = 0; \n    //cmds[0].baseInstance = 0;   \n\n    float offset = 0.0;\n    vec4 pixel = imageLoad(road_mask, ivec2(512/2, 512/2)); //center of the image\n    if (pixel.x > 0.0) {\n        offset = 1.0;\n    }\n\n    for (int i; i<curves[idx].points_count; i++) {\n        vec4 pt_position = curves[idx].positions[i];\n         transforms[instance_offset+i] = transpose(mat4(\n            0.1, 0.0, 0.0, pt_position.x,\n            0.0, 0.1, 0.0, pt_position.y,\n            0.0, 0.0, 0.1, pt_position.z,\n            0.0, 0.0, 0.0, 1.0\n        ));\n    }\n\n    //for (int i=0; i<3; i++) {\n    //\n    //    transforms[i] = transpose(mat4(\n    //        1.0, 0.0, 0.0, 0.0,\n    //        0.0, 1.0, 0.0, float(i*1.5) + offset,\n    //        0.0, 0.0, 1.0, 0.0,\n    //        0.0, 0.0, 0.0, 1.0\n    //    ));\n    //}\n}  "', src/main.rs:189:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by anopara** [comment]
ah, my bad, probably committed with a typo and didn't push subsequent commits 😅 the latest should compile

**Comment by kvark** [comment]
Sorry, it still doesn't work:
```
ERROR [country_slice::render::shader] 0:0(0): error: Read from write-only variable `cmds'

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "ERROR::SHADER::COMPILATION_FAILED\n0:0(0): error: Read from write-only variable `cmds'\n"', src/main.rs:193:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG [hotwatch::util] sender disconnected! the watcher is dead 💀
```

FYI, shaders can often break because we don't compile them with the rest of the code, and we rarely test them on CI.
To address this, we often do a build step to check all shaders for correctness, like here - https://github.com/gfx-rs/wgpu/blob/a8cf45da2d11c0bb26c845658f489cd9d4c5ade6/wgpu/tests/example_wgsl.rs#L43

**Comment by anopara** [comment]
huh, sorry about that... hm, I'm not getting this error (even though it's a valid one and I can see where its coming from) ... noob question 😓 do you know a starting point from where I can investigate why it still runs for me & that error is not visible? :(

> To address this, we often do a build step to check all shaders for correctness, like here - https://github.com/gfx-rs/wgpu/blob/a8cf45da2d11c0bb26c845658f489cd9d4c5ade6/wgpu/tests/example_wgsl.rs#L43

if I understand correctly, it will throw an error on `unwrap` if the shader cannot be parsed? or is it the `validate(&module)` you are referring to?

PS: and thanks for reporting this! 🙏

**Comment by kvark** [comment]
> if I understand correctly, it will throw an error on unwrap if the shader cannot be parsed? or is it the validate(&module) you are referring to?

it checks both parsing and validation for us and panics if anything is wrong

> do you know a starting point from where I can investigate why it still runs for me & that error is not visible? :(

Because OpenGL/GLSL isn't very portable - each driver is free to reinterpret the spec as it feels right, and the conformance tests aren't comprehensive enough.
In your case, you are using atomics on a write-only buffer. I'd expect atomics to require read access as well, so I agree with the error. Removing `writeonly` makes it build fine and even run. However, then I run into #4

**Comment by anopara** [comment]
Thank you for the reply! 🙇 

I tried Vulkan's [glslangValidator](https://github.com/KhronosGroup/glslang), however, it caught neither uninitialized `i` variable nor `writeonly` 😢 

I guess I will be fixing these errors as they happen for others, which is a bit anxiety inducing 😅 

May I ask you what OS and GPU you have?

**Comment by kvark** [comment]
This was tested on Linux with "Intel(R) Xe Graphics (TGL GT2)".

**Comment by kvark** [comment]
Looks like it's still there:
```
     Running `target/debug/country-slice`
TRACE [mio::poll] registering event source with poller: token=Token(0), interests=READABLE
INFO [winit::platform_impl::platform::x11::window] Guessed window scale factor: 1.5
DEBUG [winit::platform_impl::platform::x11::window] Calculated physical dimensions: 1600x1200
INFO [country_slice::setup] Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: Some(4), srgb: true }
TRACE [mio::poll] registering with poller
TRACE [mio::poll] registering with poller
TRACE [mio::poll] registering with poller
DEBUG [country_slice::render::ssbo] Created a new storage buffer, id: 2
DEBUG [country_slice::render::ssbo] Created a new storage buffer, id: 3
ERROR [country_slice::render::shader] 0:194(53): warning: `dummy' used uninitialized
0:0(0): error: Read from write-only variable `cmds'

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "ERROR::SHADER::COMPILATION_FAILED\n0:194(53): warning: `dummy' used uninitialized\n0:0(0): error: Read from write-only variable `cmds'\n"', src/resources/compute_arches_indirect.rs:27:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG [hotwatch::util] sender disconnected! the watcher is dead 💀
```

**Comment by anopara** [comment]
Ah, missed the other one. Thank you 🙏
